// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzdv3nKOCAGgeJJsvb_IDqRErhfF1gc0g',
    appId: '1:231912637776:web:582b120ddfa4605ac11855',
    messagingSenderId: '231912637776',
    projectId: 'para-pilot-e7d52',
    authDomain: 'para-pilot-e7d52.firebaseapp.com',
    storageBucket: 'para-pilot-e7d52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoROP8f6T_L5f5ce7OtTpO5N2xblnfP4',
    appId: '1:231912637776:android:ecfe62f9a191fc02c11855',
    messagingSenderId: '231912637776',
    projectId: 'para-pilot-e7d52',
    storageBucket: 'para-pilot-e7d52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjfPXaOUrbQb_RKETtPEDTHQiIIx6Syc',
    appId: '1:231912637776:ios:5eea29d9c2c349fac11855',
    messagingSenderId: '231912637776',
    projectId: 'para-pilot-e7d52',
    storageBucket: 'para-pilot-e7d52.appspot.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjfPXaOUrbQb_RKETtPEDTHQiIIx6Syc',
    appId: '1:231912637776:ios:5eea29d9c2c349fac11855',
    messagingSenderId: '231912637776',
    projectId: 'para-pilot-e7d52',
    storageBucket: 'para-pilot-e7d52.appspot.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzdv3nKOCAGgeJJsvb_IDqRErhfF1gc0g',
    appId: '1:231912637776:web:d30734656496117dc11855',
    messagingSenderId: '231912637776',
    projectId: 'para-pilot-e7d52',
    authDomain: 'para-pilot-e7d52.firebaseapp.com',
    storageBucket: 'para-pilot-e7d52.appspot.com',
  );
}
